// <auto-generated />
namespace RestoranSiteV2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class t : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(t));
        
        string IMigrationMetadata.Id
        {
            get { return "202412211039499_t"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
